[package]
name = "v86_64"
version = "0.1.0"
publish = false
edition = "2021"

[features]
default = []
profiler = []
# guest RAM in a separate 64-bit memory (up to 16 GiB), see src/rust/cpu/guest.rs
mem64 = []

[lib]
crate-type = ["cdylib"]
path = "src/rust/lib.rs"

[profile.test]
lto = false
opt-level = 2
overflow-checks = false

[profile.dev]
lto = true
opt-level = 2
panic = "abort"
overflow-checks = false

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
panic = "abort"
